# Generated by Django 5.0.1 on 2026-05-27 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='farm', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='field',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='farms.farm'),
        ),
        migrations.AddField(
            model_name='cropplanting',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantings', to='farms.field'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='farms.farm'),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_data', to='farms.farm'),
        ),
        migrations.AddField(
            model_name='yieldprediction',
            name='planting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='farms.cropplanting'),
        ),
        migrations.AddField(
            model_name='yieldrecord',
            name='planting',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='planting_yields', to='farms.cropplanting'),
        ),
        migrations.AlterUniqueTogether(
            name='weatherdata',
            unique_together={('farm', 'date')},
        ),
    ]
