# Generated by Django 5.0.1 on 2026-05-29 00:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(help_text='e.g. Long Rains, Dry Season', max_length=50)),
                ('season_year', models.PositiveIntegerField()),
                ('resource_type', models.CharField(choices=[('fertilizer', 'Fertilizer'), ('pesticide', 'Pesticide'), ('water', 'Water'), ('seed', 'Seed')], max_length=20)),
                ('quantity', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('unit', models.CharField(choices=[('kg', 'Kilograms (kg)'), ('liters', 'Liters'), ('bags', 'Bags'), ('m3', 'Cubic meters (m3)')], max_length=20)),
                ('cost', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('application_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_usages', to='farms.field')),
            ],
            options={
                'verbose_name': 'Input Usage',
                'verbose_name_plural': 'Input Usages',
                'ordering': ['-application_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='inputusage',
            index=models.Index(fields=['field', 'season_year', 'season'], name='farms_input_field_i_17bc7f_idx'),
        ),
        migrations.AddIndex(
            model_name='inputusage',
            index=models.Index(fields=['resource_type'], name='farms_input_resourc_457f4b_idx'),
        ),
    ]
