# Generated by Django 5.0.1 on 2026-05-29 00:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0003_inputusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='nutrient_content',
            field=models.FloatField(blank=True, help_text='Nutrient content score (%)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
