# Generated by Django 5.0.1 on 2026-05-29 00:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0004_field_nutrient_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='PestDiseaseAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('fungal', 'Fungal Risk'), ('disease', 'Disease Risk'), ('pest', 'Pest Pressure')], max_length=20)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('season', models.CharField(blank=True, max_length=50)),
                ('triggered_weather_date', models.DateField(blank=True, null=True)),
                ('rainfall_mm', models.FloatField(default=0)),
                ('humidity_percent', models.IntegerField(default=0)),
                ('temperature_c', models.FloatField(default=0)),
                ('risk_score', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pest_disease_alerts', to='farms.crop')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pest_disease_alerts', to='farms.farm')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pest_disease_alerts', to='farms.field')),
            ],
            options={
                'verbose_name': 'Pest Disease Alert',
                'verbose_name_plural': 'Pest Disease Alerts',
                'ordering': ['-risk_score', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='pestdiseasealert',
            index=models.Index(fields=['farm', 'is_acknowledged', 'risk_level'], name='farms_pest_farm_i_4b2c3e_idx'),
        ),
        migrations.AddIndex(
            model_name='pestdiseasealert',
            index=models.Index(fields=['alert_type', 'risk_level'], name='farms_pest_type_ris_7a9d1d_idx'),
        ),
    ]
