# Generated by Django 4.2.30 on 2026-07-03 12:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('farms', '0005_pestdiseasealert'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='inputusage',
            new_name='farms_input_field_i_b58d67_idx',
            old_name='farms_input_field_i_17bc7f_idx',
        ),
        migrations.RenameIndex(
            model_name='inputusage',
            new_name='farms_input_resourc_7ff1b7_idx',
            old_name='farms_input_resourc_457f4b_idx',
        ),
        migrations.RenameIndex(
            model_name='pestdiseasealert',
            new_name='farms_pestd_farm_id_d342ad_idx',
            old_name='farms_pest_farm_i_4b2c3e_idx',
        ),
        migrations.RenameIndex(
            model_name='pestdiseasealert',
            new_name='farms_pestd_alert_t_a2adf9_idx',
            old_name='farms_pest_type_ris_7a9d1d_idx',
        ),
        migrations.AddField(
            model_name='farm',
            name='extension_officers',
            field=models.ManyToManyField(blank=True, related_name='assigned_farms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inputusage',
            name='active_ingredient',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='inputusage',
            name='cost_per_unit',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='inputusage',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inputusage',
            name='input_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='inputusage',
            name='irrigation_method',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='inputusage',
            name='planting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='input_usages', to='farms.cropplanting'),
        ),
        migrations.AddField(
            model_name='inputusage',
            name='total_cost',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='is_dismissed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='yieldprediction',
            name='estimated_harvest_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='yieldprediction',
            name='feature_importance',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='yieldprediction',
            name='predicted_yield_per_hectare',
            field=models.FloatField(default=0, help_text='Predicted yield per hectare in kg'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inputusage',
            name='resource_type',
            field=models.CharField(choices=[('fertilizer', 'Fertilizer'), ('pesticide', 'Pesticide'), ('herbicide', 'Herbicide'), ('irrigation', 'Irrigation'), ('seed', 'Seed'), ('labour', 'Labour')], max_length=20),
        ),
    ]
